spring:
  profiles:
    active: prod
  application:
    name: VOTE-SERVICE
  jpa:
    open-in-view: false
  config:
    import: optional:configserver:http//localhost:8888
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
