spring:
  profiles:
    active: dev
  application:
    name: ADMIN-SERVICE
  jpa:
    open-in-view: false
  jackson:
    date-format: yyyy-MM-dd
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
    shutdown:
      enabled: true
  info:
    env:
      enabled: true
info:
  app:
    name: "Spring Boot Restfull Web Services"
    description: "Spring Boot Restful Web Services Demo"
    version: "1.0.0"
  application:
    name: ADMIN-SERVICE
  jpa:
    open-in-view: false
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
